if not Talented_Data then return end

Talented_Data.SHAMAN = {
	{
		numtalents = 15,
		talents = {
			{
				info = {
					name = "Convection",
					ranks = 5,
					column = 2,
					icon = 136116,
					row = 1,
					tips = "Reduces the mana cost of your Shock, Lightning Bolt and Chain Lightning spells by 2%.",
				},
			}, -- [1]
			{
				info = {
					name = "Concussion",
					ranks = 5,
					column = 3,
					icon = 135807,
					row = 1,
					tips = "Increases the damage done by your Lightning Bolt, Chain Lightning and Shock spells by 1%.",
				},
			}, -- [2]
			{
				info = {
					name = "Earth's Grasp",
					ranks = 2,
					column = 1,
					icon = 136097,
					row = 2,
					tips = "Increases the health of your Stoneclaw Totem by 25% and the radius of your Earthbind Totem by 10%.",
				},
			}, -- [3]
			{
				info = {
					name = "Elemental Warding",
					ranks = 3,
					column = 2,
					icon = 136094,
					row = 2,
					tips = "Reduces damage taken from Fire, Frost and Nature effects by 4%.",
				},
			}, -- [4]
			{
				info = {
					name = "Call of Flame",
					ranks = 3,
					column = 3,
					icon = 135817,
					row = 2,
					tips = "Increases the damage done by your Fire Totems by 5%.",
				},
			}, -- [5]
			{
				info = {
					ranks = 1,
					name = "Elemental Focus",
					icon = 136170,
					column = 1,
					exceptional = 1,
					row = 3,
					tips = "Gives you a 10% chance to enter a Clearcasting state after casting any Fire, Frost, or Nature damage spell.  The Clearcasting state reduces the mana cost of your next damage spell by 100%.",
				},
			}, -- [6]
			{
				info = {
					name = "Reverberation",
					ranks = 5,
					column = 2,
					icon = 135850,
					row = 3,
					tips = "Reduces the cooldown of your Shock spells by 0.2 sec.",
				},
			}, -- [7]
			{
				info = {
					name = "Call of Thunder",
					ranks = 5,
					column = 3,
					icon = 136014,
					row = 3,
					tips = "Increases the critical strike chance of your Lightning Bolt and Chain Lightning spells by an additional 1%.",
				},
			}, -- [8]
			{
				info = {
					name = "Improved Fire Totems",
					ranks = 2,
					column = 1,
					icon = 135824,
					row = 4,
					tips = "Reduces the delay before your Fire Nova Totem activates by 1 sec. and decreases the threat generated by your Magma Totem by 25%.",
				},
			}, -- [9]
			{
				info = {
					name = "Eye of the Storm",
					ranks = 3,
					column = 2,
					icon = 136032,
					row = 4,
					tips = "Gives you a 33% chance to gain the Focused Casting effect that lasts for 6 sec after being the victim of a melee or ranged critical strike.  The Focused Casting effect prevents you from losing casting time when taking damage.",
				},
			}, -- [10]
			{
				info = {
					name = "Elemental Devastation",
					ranks = 3,
					column = 4,
					icon = 135791,
					row = 4,
					tips = "Your offensive spell crits will increase your chance to get a critical strike with melee attacks by 3% for 10 sec.",
				},
			}, -- [11]
			{
				info = {
					name = "Storm Reach",
					ranks = 2,
					column = 1,
					icon = 136099,
					row = 5,
					tips = "Increases the range of your Lightning Bolt and Chain Lightning spells by 3 yards.",
				},
			}, -- [12]
			{
				info = {
					name = "Elemental Fury",
					ranks = 1,
					column = 2,
					icon = 135830,
					row = 5,
					tips = "Increases the critical strike damage bonus of your Searing, Magma, and Fire Nova Totems and your Fire, Frost, and Nature spells by 100%.",
				},
			}, -- [13]
			{
				info = {
					prereqs = {
						{
							column = 3,
							row = 3,
							source = 8,
						}, -- [1]
					},
					name = "Lightning Mastery",
					ranks = 5,
					column = 3,
					icon = 135990,
					row = 6,
					tips = "Reduces the cast time of your Lightning Bolt and Chain Lightning spells by 0.2 sec.",
				},
			}, -- [14]
			{
				info = {
					ranks = 1,
					prereqs = {
						{
							column = 2,
							row = 5,
							source = 13,
						}, -- [1]
					},
					name = "Elemental Mastery",
					icon = 136115,
					column = 2,
					exceptional = 1,
					row = 7,
					tips = "When activated, this spell gives your next Fire, Frost, or Nature damage spell a 100% critical strike chance and reduces the mana cost by 100%.",
				},
			}, -- [15]
		},
		info = {
			name = "Elemental",
			background = "ShamanElementalCombat",
		},
	}, -- [1]
	{
		numtalents = 16,
		talents = {
			{
				info = {
					name = "Ancestral Knowledge",
					ranks = 5,
					column = 2,
					icon = 136162,
					row = 1,
					tips = "Increases your maximum Mana by 1%.",
				},
			}, -- [1]
			{
				info = {
					name = "Shield Specialization",
					ranks = 5,
					column = 3,
					icon = 134952,
					row = 1,
					tips = "Increases your chance to block attacks with a shield by 1% and increases the amount blocked by 5%.",
				},
			}, -- [2]
			{
				info = {
					name = "Guardian Totems",
					ranks = 2,
					column = 1,
					icon = 136098,
					row = 2,
					tips = "Increases the amount of damage reduced by your Stoneskin Totem and Windwall Totem by 10% and reduces the cooldown of your Grounding Totem by 1 sec.",
				},
			}, -- [3]
			{
				info = {
					name = "Thundering Strikes",
					ranks = 5,
					column = 2,
					icon = 132325,
					row = 2,
					tips = "Improves your chance to get a critical strike with your weapon attacks by 1%.",
				},
			}, -- [4]
			{
				info = {
					name = "Improved Ghost Wolf",
					ranks = 2,
					column = 3,
					icon = 136095,
					row = 2,
					tips = "Reduces the cast time of your Ghost Wolf spell by 1 sec.",
				},
			}, -- [5]
			{
				info = {
					name = "Improved Lightning Shield",
					ranks = 3,
					column = 4,
					icon = 136051,
					row = 2,
					tips = "Increases the damage done by your Lightning Shield orbs by 5%.",
				},
			}, -- [6]
			{
				info = {
					name = "Enhancing Totems",
					ranks = 2,
					column = 1,
					icon = 136023,
					row = 3,
					tips = "Increases the effect of your Strength of Earth and Grace of Air Totems by 8%.",
				},
			}, -- [7]
			{
				info = {
					name = "Two-Handed Axes and Maces",
					ranks = 1,
					column = 3,
					icon = 132401,
					row = 3,
					tips = "Allows you to use Two-Handed Axes and Two-Handed Maces.",
				},
			}, -- [8]
			{
				info = {
					name = "Anticipation",
					ranks = 5,
					column = 4,
					icon = 136056,
					row = 3,
					tips = "Increases your chance to dodge by an additional 1%.",
				},
			}, -- [9]
			{
				info = {
					prereqs = {
						{
							column = 2,
							row = 2,
							source = 4,
						}, -- [1]
					},
					name = "Flurry",
					ranks = 5,
					column = 2,
					icon = 132152,
					row = 4,
					tips = "Increases your attack speed by 10% for your next 3 swings after dealing a critical strike.",
				},
			}, -- [10]
			{
				info = {
					name = "Toughness",
					ranks = 5,
					column = 3,
					icon = 135892,
					row = 4,
					tips = "Increases your armor value from items by 2%.",
				},
			}, -- [11]
			{
				info = {
					name = "Improved Weapon Totems",
					ranks = 2,
					column = 1,
					icon = 135792,
					row = 5,
					tips = "Increases the melee attack power bonus of your Windfury Totem by 15% and increases the damage caused by your Flametongue Totem by 6%.",
				},
			}, -- [12]
			{
				info = {
					name = "Elemental Weapons",
					ranks = 3,
					column = 2,
					icon = 135814,
					row = 5,
					tips = "Increases the melee attack power bonus of your Rockbiter Weapon by 7%, your Windfury Weapon effect by 13% and increases the damage caused by your Flametongue Weapon and Frostbrand Weapon by 5%.",
				},
			}, -- [13]
			{
				info = {
					name = "Parry",
					ranks = 1,
					column = 3,
					icon = 132269,
					row = 5,
					tips = "Gives a chance to parry enemy melee attacks.",
				},
			}, -- [14]
			{
				info = {
					name = "Weapon Mastery",
					ranks = 5,
					column = 3,
					icon = 132215,
					row = 6,
					tips = "Increases the damage you deal with all weapons by 2%.",
				},
			}, -- [15]
			{
				info = {
					ranks = 1,
					prereqs = {
						{
							column = 2,
							row = 5,
							source = 13,
						}, -- [1]
					},
					name = "Stormstrike",
					icon = 135963,
					column = 2,
					exceptional = 1,
					row = 7,
					tips = "Gives you an extra attack.  In addition, the next 2 sources of Nature damage dealt to the target are increased by 20%.  Lasts 12 sec.",
				},
			}, -- [16]
		},
		info = {
			name = "Enhancement",
			background = "ShamanEnhancement",
		},
	}, -- [2]
	{
		numtalents = 15,
		talents = {
			{
				info = {
					name = "Improved Healing Wave",
					ranks = 5,
					column = 2,
					icon = 136052,
					row = 1,
					tips = "Reduces the casting time of your Healing Wave spell by 0.1 sec.",
				},
			}, -- [1]
			{
				info = {
					name = "Tidal Focus",
					ranks = 5,
					column = 3,
					icon = 135859,
					row = 1,
					tips = "Reduces the Mana cost of your healing spells by 1%.",
				},
			}, -- [2]
			{
				info = {
					name = "Improved Reincarnation",
					ranks = 2,
					column = 1,
					icon = 136080,
					row = 2,
					tips = "Reduces the cooldown of your Reincarnation spell by 10 min and increases the amount of health and mana you reincarnate with by an additional 10%.",
				},
			}, -- [3]
			{
				info = {
					name = "Ancestral Healing",
					ranks = 3,
					column = 2,
					icon = 136109,
					row = 2,
					tips = "Increases your target's armor value by 8% for 15 sec after getting a critical effect from one of your healing spells.",
				},
			}, -- [4]
			{
				info = {
					name = "Totemic Focus",
					ranks = 5,
					column = 3,
					icon = 136057,
					row = 2,
					tips = "Reduces the Mana cost of your totems by 5%.",
				},
			}, -- [5]
			{
				info = {
					name = "Nature's Guidance",
					ranks = 3,
					column = 1,
					icon = 135860,
					row = 3,
					tips = "Increases your chance to hit with melee attacks and spells by 1%.",
				},
			}, -- [6]
			{
				info = {
					name = "Healing Focus",
					ranks = 5,
					column = 2,
					icon = 136043,
					row = 3,
					tips = "Gives you a 14% chance to avoid interruption caused by damage while casting any healing spell.",
				},
			}, -- [7]
			{
				info = {
					name = "Totemic Mastery",
					ranks = 1,
					column = 3,
					icon = 136069,
					row = 3,
					tips = "The radius of your totems that affect friendly targets is increased to 30 yd.",
				},
			}, -- [8]
			{
				info = {
					name = "Healing Grace",
					ranks = 3,
					column = 4,
					icon = 136041,
					row = 3,
					tips = "Reduces the threat generated by your healing spells by 5%.",
				},
			}, -- [9]
			{
				info = {
					name = "Restorative Totems",
					ranks = 5,
					column = 2,
					icon = 136053,
					row = 4,
					tips = "Increases the effect of your Mana Spring and Healing Stream Totems by 5%.",
				},
			}, -- [10]
			{
				info = {
					name = "Tidal Mastery",
					ranks = 5,
					column = 3,
					icon = 136107,
					row = 4,
					tips = "Increases the critical effect chance of your healing and lightning spells by 1%.",
				},
			}, -- [11]
			{
				info = {
					name = "Healing Way",
					ranks = 3,
					column = 1,
					icon = 136044,
					row = 5,
					tips = "Your Healing Wave spells have a 33% chance to increase the effect of subsequent Healing Wave spells on that target by 6% for 15 sec.  This effect will stack up to 3 times.",
				},
			}, -- [12]
			{
				info = {
					ranks = 1,
					name = "Nature's Swiftness",
					icon = 136076,
					column = 3,
					exceptional = 1,
					row = 5,
					tips = "When activated, your next Nature spell with a casting time less than 10 sec. becomes an instant cast spell.",
				},
			}, -- [13]
			{
				info = {
					name = "Purification",
					ranks = 5,
					column = 3,
					icon = 135865,
					row = 6,
					tips = "Increases the effectiveness of your healing spells by 2%.",
				},
			}, -- [14]
			{
				info = {
					ranks = 1,
					prereqs = {
						{
							column = 2,
							row = 4,
							source = 10,
						}, -- [1]
					},
					name = "Mana Tide Totem",
					icon = 135861,
					column = 2,
					exceptional = 1,
					row = 7,
					tips = "Summons a Mana Tide Totem with 5 health at the feet of the caster for 12 sec that restores 170 mana every 3 seconds to group members within 20 yards.",
				},
			}, -- [15]
		},
		info = {
			name = "Restoration",
			background = "ShamanRestoration",
		},
	} -- [3]
}
