if not Talented_Data then return end

Talented_Data.DRUID = {
	{
		numtalents = 28,
		talents = {
			{
				info = {
					tips = "Reduces the cast time of your Wrath and Starfire spells by %.1f sec.",
					tipValues = {{0.1}, {0.2}, {0.3}, {0.4}, {0.5}},
					name = "Starlight Wrath",
					column = 2,
					row = 1,
					icon = 136006,
					ranks = 5,
				},
			}, -- [1]
			{
				info = {
					tips = "Increases the damage and healing done by your periodic spell damage and healing effects by %d%%.",
					tipValues = {{1}, {2}, {3}, {4}, {5}},
					name = "Genesis",
					column = 3,
					row = 1,
					icon = 135730,
					ranks = 5,
				},
			}, -- [2]
			{
				info = {
					tips = "Reduces the Mana cost of your Moonfire, Starfire, Starfall, Wrath, Healing Touch, Nourish, Regrowth and Rejuvenation spells by %d%%.",
					tipValues = {{3}, {6}, {9}},
					name = "Moonglow",
					column = 1,
					row = 2,
					icon = 136087,
					ranks = 3,
				},
			}, -- [3]
			{
				info = {
					tips = "Increases the critical strike chance of your Wrath, Starfire, Starfall, Nourish and Healing Touch spells by %d%%.",
					tipValues = {{2}, {4}},
					name = "Nature's Majesty",
					column = 2,
					row = 2,
					icon = 135138,
					ranks = 2,
				},
			}, -- [4]
			{
				info = {
					tips = "Increases the damage and critical strike chance of your Moonfire spell by %d%%.",
					tipValues = {{5}, {10}},
					name = "Improved Moonfire",
					column = 4,
					row = 2,
					icon = 136096,
					ranks = 2,
				},
			}, -- [5]
			{
				info = {
					tips = "Damage from your Thorns and Entangling Roots increased by %d%% and damage done by your Treants increased by %d%%. In addition, damage from your Treants and attacks done to you while you have Barkskin active have a %d%% chance to daze the target for 3 sec.",
					tipValues = {{25, 5, 10}, {50, 10, 10}, {75, 15, 15}},
					name = "Brambles",
					column = 1,
					row = 3,
					icon = 136104,
					ranks = 3,
				},
			}, -- [6]
			{
				info = {
					tips = "All non-periodic spell criticals have a %d%% chance to grace you with a blessing of nature, increasing your spell casting speed by 20%% for 3 sec.",
					tipValues = {{33}, {66}, {100}},
					prereqs = {
						{
							column = 2,
							row = 2,
							source = 4,
						}, -- [1]
						{
						}, -- [2]
					},
					name = "Nature's Grace",
					column = 2,
					row = 3,
					icon = 136062,
					ranks = 3,
				},
			}, -- [7]
			{
				info = {
					tips = "Increases the duration of your Moonfire and Rejuvenation spells by 3 sec, your Regrowth spell by 6 sec, and your Insect Swarm and Lifebloom spells by 2 sec.",
					prereqs = {
						{
							column = 2,
							row = 2,
							source = 4,
						}, -- [1]
						{
						}, -- [2]
					},
					name = "Nature's Splendor",
					column = 3,
					row = 3,
					icon = 136060,
					ranks = 1,
				},
			}, -- [8]
			{
				info = {
					tips = "Increases the range of your Balance spells and Faerie Fire (Feral) ability by %d%%, and reduces the threat generated by your Balance spells by %d%%.",
					tipValues = {{10, 15}, {20, 30}},
					name = "Nature's Reach",
					column = 4,
					row = 3,
					icon = 136065,
					ranks = 2,
				},
			}, -- [9]
			{
				info = {
					tips = "Increases the critical strike damage bonus of your Starfire, Starfall, Moonfire, and Wrath spells by %d%%.",
					tipValues = {{20}, {40}, {60}, {80}, {100}},
					name = "Vengeance",
					column = 2,
					row = 4,
					icon = 136075,
					ranks = 5,
				},
			}, -- [10]
			{
				info = {
					tips = "Reduces the pushback suffered from damaging attacks while casting Starfire, Hibernate and Hurricane by %d%% and increases your total spell haste by %d%%.",
					tipValues = {{23, 1}, {46, 2}, {70, 3}},
					name = "Celestial Focus",
					column = 3,
					row = 4,
					icon = 135753,
					ranks = 3,
				},
			}, -- [11]
			{
				info = {
					tips = "Increases your spell power by %d%% of your total Intellect.",
					tipValues = {{4}, {8}, {12}},
					name = "Lunar Guidance",
					column = 1,
					row = 5,
					icon = 132132,
					ranks = 3,
				},
			}, -- [12]
			{
				info = {
					tips = "The enemy target is swarmed by insects, decreasing their chance to hit by 3%% and causing 144 Nature damage over 12 sec.",
					name = "Insect Swarm",
					exceptional = 1,
					column = 2,
					row = 5,
					icon = 136045,
					ranks = 1,
				},
			}, -- [13]
			{
				info = {
					tips = "Increases your damage done by your Wrath spell to targets afflicted by your Insect Swarm by %d%%, and increases the critical strike chance of your Starfire spell by %d%% on targets afflicted by your Moonfire spell.",
					tipValues = {{1, 1}, {2, 2}, {3, 3}},
					prereqs = {
						{
							column = 2,
							row = 5,
							source = 13,
						}, -- [1]
						{
						}, -- [2]
					},
					name = "Improved Insect Swarm",
					column = 3,
					row = 5,
					icon = 136045,
					ranks = 3,
				},
			}, -- [14]
			{
				info = {
					tips = "Regenerate mana equal to %d%% of your Intellect every 5 sec, even while casting.",
					tipValues = {{4}, {7}, {10}},
					name = "Dreamstate",
					column = 1,
					row = 6,
					icon = 132123,
					ranks = 3,
				},
			}, -- [15]
			{
				info = {
					tips = "Increases the damage done by your Starfire, Moonfire and Wrath spells by %d%%.",
					tipValues = {{3}, {6}, {10}},
					name = "Moonfury",
					column = 2,
					row = 6,
					icon = 136057,
					ranks = 3,
				},
			}, -- [16]
			{
				info = {
					tips = "Increases your chance to hit with all spells by %d%% and reduces your damage taken from all spells by %d%%.",
					tipValues = {{2, 3}, {4, 6}},
					name = "Balance of Power",
					column = 3,
					row = 6,
					icon = 132113,
					ranks = 2,
				},
			}, -- [17]
			{
				info = {
					tips = "Shapeshift into Moonkin Form.  While in this form the armor contribution from items is increased by 370%%, damage taken while stunned is reduced by 15%%, and all party and raid members within 100 yards have their spell critical chance increased by 5%%.  Single target spell critical strikes in this form instantly regenerate 2%% of your total mana.  The Moonkin can not cast healing or resurrection spells while shapeshifted.\r\n\r\nThe act of shapeshifting frees the caster of Polymorph and Movement Impairing effects.",
					name = "Moonkin Form",
					exceptional = 1,
					column = 2,
					row = 7,
					icon = 136036,
					ranks = 1,
				},
			}, -- [18]
			{
				info = {
					tips = "Your Moonkin Aura also causes affected targets to gain %d%% haste and you to gain %d%% of your spirit as additional spell damage.",
					tipValues = {{1, 10}, {2, 20}, {3, 30}},
					prereqs = {
						{
							column = 2,
							row = 7,
							source = 18,
						}, -- [1]
						{
						}, -- [2]
					},
					name = "Improved Moonkin Form",
					column = 3,
					row = 7,
					icon = 236156,
					ranks = 3,
				},
			}, -- [19]
			{
				info = {
					tips = "Your Faerie Fire spell also increases the chance the target will be hit by spell attacks by %d%%, and increases the critical strike chance of your damage spells by %d%% on targets afflicted by Faerie Fire.",
					tipValues = {{1, 1}, {2, 2}, {3, 3}},
					name = "Improved Faerie Fire",
					column = 4,
					row = 7,
					icon = 136033,
					ranks = 3,
				},
			}, -- [20]
			{
				info = {
					tips = "Attacks done to you while in Moonkin form have a %d%% chance to cause you to go into a Frenzy, increasing your damage by 10%%, cause you to be immune to pushback while casting Balance spells and restore 2%% base mana every 2 sec. Lasts 10 sec.",
					tipValues = {{5}, {10}, {15}},
					prereqs = {
						{
							column = 2,
							row = 7,
							source = 18,
						}, -- [1]
						{
						}, -- [2]
					},
					name = "Owlkin Frenzy",
					column = 1,
					row = 8,
					icon = 236163,
					ranks = 3,
				},
			}, -- [21]
			{
				info = {
					tips = "Your Starfire spell gains an additional %d%% and your Wrath gains an additional %d%% of your bonus damage effects.",
					tipValues = {{4, 2}, {8, 4}, {12, 6}, {16, 8}, {20, 10}},
					name = "Wrath of Cenarius",
					column = 3,
					row = 8,
					icon = 132146,
					ranks = 5,
				},
			}, -- [22]
			{
				info = {
					tips = "When you critically hit with Starfire, you have a %d%% chance of increasing damage done by Wrath by 40%%. When you critically hit with Wrath, you have a %d%% chance of increasing your critical strike chance with Starfire by 40%%. Each effect lasts 15 sec and each has a separate 30 sec cooldown.  Both effects cannot occur simultaneously.",
					tipValues = {{33, 20}, {66, 40}, {100, 60}},
					name = "Eclipse",
					column = 1,
					row = 9,
					icon = 236151,
					ranks = 3,
				},
			}, -- [23]
			{
				info = {
					tips = "You summon a violent Typhoon that does 400 Nature damage when in contact with hostile targets, knocking them back and dazing them for 6 sec.",
					prereqs = {
						{
							column = 2,
							row = 7,
							source = 18,
						}, -- [1]
						{
						}, -- [2]
					},
					name = "Typhoon",
					exceptional = 1,
					column = 2,
					row = 9,
					icon = 236170,
					ranks = 1,
				},
			}, -- [24]
			{
				info = {
					tips = "Summons 3 treants to attack enemy targets for 30 sec.",
					name = "Force of Nature",
					exceptional = 1,
					column = 3,
					row = 9,
					icon = 132129,
					ranks = 1,
				},
			}, -- [25]
			{
				info = {
					tips = "Increases damage done by your Hurricane and Typhoon spells by %d%%, and increases the range of your Cyclone spell by %d yards.",
					tipValues = {{15, 2}, {30, 4}},
					name = "Gale Winds",
					column = 4,
					row = 9,
					icon = 236154,
					ranks = 2,
				},
			}, -- [26]
			{
				info = {
					tips = "Your Wrath and Starfire spells have a 100%% chance to apply the Earth and Moon effect, which increases spell damage taken by %d%% for 12 sec.  Also increases your spell damage by %d%%.",
					tipValues = {{4, 2}, {9, 4}, {13, 6}},
					name = "Earth and Moon",
					column = 2,
					row = 10,
					icon = 236150,
					ranks = 3,
				},
			}, -- [27]
			{
				info = {
					tips = "You summon a flurry of stars from the sky on all targets within 30 yards of the caster, each dealing 145 to 167 Arcane damage. Also causes 26 Arcane damage to all other enemies within 5 yards of the enemy target. Maximum 20 stars. Lasts 10 sec.  Shapeshifting into an animal form or mounting cancels the effect. Any effect which causes you to lose control of your character will suppress the starfall effect.",
					name = "Starfall",
					exceptional = 1,
					column = 2,
					row = 11,
					icon = 236168,
					ranks = 1,
				},
			}, -- [28]
		},
		info = {
			background = "DruidBalance",
			name = "Balance",
			icon = 136096,
		},
	}, -- [1]
	{
		numtalents = 30,
		talents = {
			{
				info = {
					tips = "Reduces the cost of your Maul, Swipe, Claw, Rake and Mangle abilities by %d Rage or Energy.",
					tipValues = {{1}, {2}, {3}, {4}, {5}},
					name = "Ferocity",
					column = 2,
					row = 1,
					icon = 132190,
					ranks = 5,
				},
			}, -- [1]
			{
				info = {
					tips = "Increases the attack power reduction of your Demoralizing Roar by %d%% and the damage caused by your Ferocious Bite by %d%%.",
					tipValues = {{8, 3}, {16, 6}, {24, 9}, {32, 12}, {40, 15}},
					name = "Feral Aggression",
					column = 3,
					row = 1,
					icon = 132121,
					ranks = 5,
				},
			}, -- [2]
			{
				info = {
					tips = "Increases the damage done by your Swipe ability by %d%% and reduces the chance enemies have to detect you while Prowling.",
					tipValues = {{10}, {20}, {30}},
					name = "Feral Instinct",
					column = 1,
					row = 2,
					icon = 132089,
					ranks = 3,
				},
			}, -- [3]
			{
				info = {
					tips = "Increases the damage caused by your Claw, Rake, Mangle (Cat), Mangle (Bear), and Maul abilities by %d%%.",
					tipValues = {{10}, {20}},
					name = "Savage Fury",
					column = 2,
					row = 2,
					icon = 132141,
					ranks = 2,
				},
			}, -- [4]
			{
				info = {
					tips = "Increases your Armor contribution from cloth and leather items by %d%%.",
					tipValues = {{4}, {7}, {10}},
					name = "Thick Hide",
					column = 3,
					row = 2,
					icon = 134355,
					ranks = 3,
				},
			}, -- [5]
			{
				info = {
					tips = "Increases your movement speed by %d%% in Cat Form and increases your chance to dodge while in Cat Form, Bear Form and Dire Bear Form by %d%%.",
					tipValues = {{15, 2}, {30, 4}},
					name = "Feral Swiftness",
					column = 1,
					row = 3,
					icon = 136095,
					ranks = 2,
				},
			}, -- [6]
			{
				info = {
					tips = "When activated, this ability temporarily grants you 30%% of your maximum health for 20 sec while in Bear Form, Cat Form, or Dire Bear Form.  After the effect expires, the health is lost.",
					name = "Survival Instincts",
					exceptional = 1,
					column = 2,
					row = 3,
					icon = 236169,
					ranks = 1,
				},
			}, -- [7]
			{
				info = {
					tips = "Increases your critical strike chance while in Bear, Dire Bear or Cat Form by %d%%.",
					tipValues = {{2}, {4}, {6}},
					name = "Sharpened Claws",
					column = 3,
					row = 3,
					icon = 134297,
					ranks = 3,
				},
			}, -- [8]
			{
				info = {
					tips = "Reduces the energy cost of your Shred ability by %d and the rage cost of your Lacerate ability by %d.",
					tipValues = {{9, 1}, {18, 2}},
					name = "Shredding Attacks",
					column = 1,
					row = 4,
					icon = 136231,
					ranks = 2,
				},
			}, -- [9]
			{
				info = {
					tips = "Increases your melee attack power in Cat, Bear and Dire Bear Forms by %d%% of your level and %d%% of any attack power on your equipped weapon.  In addition, your finishing moves have a %d%% chance per combo point to make your next Nature spell with a base casting time less than 10 sec. become an instant cast spell.",
					tipValues = {{50, 7, 7}, {100, 14, 13}, {150, 20, 20}},
					name = "Predatory Strikes",
					column = 2,
					row = 4,
					icon = 132185,
					ranks = 3,
				},
			}, -- [10]
			{
				info = {
					tips = "Gives you a %d%% chance to gain an additional 5 Rage anytime you get a critical strike while in Bear and Dire Bear Form and your critical strikes from Cat Form abilities that add combo points  have a %d%% chance to add an additional combo point.",
					tipValues = {{50, 50}, {100, 100}},
					prereqs = {
						{
							column = 3,
							row = 3,
							source = 8,
						}, -- [1]
						{
						}, -- [2]
					},
					name = "Primal Fury",
					column = 3,
					row = 4,
					icon = 132278,
					ranks = 2,
				},
			}, -- [11]
			{
				info = {
					tips = "Increases your expertise by %d, and you are refunded %d%% of the energy cost of a finishing move if it fails to land.",
					tipValues = {{5, 40}, {10, 80}},
					prereqs = {
						{
							column = 3,
							row = 3,
							source = 8,
						}, -- [1]
						{
						}, -- [2]
					},
					name = "Primal Precision",
					column = 4,
					row = 4,
					icon = 236165,
					ranks = 2,
				},
			}, -- [12]
			{
				info = {
					tips = "Increases the stun duration of your Bash and Pounce abilities by %.1f sec and decreases the cooldown of Bash by %d sec.",
					tipValues = {{0.5, 15}, {1.0, 30}},
					name = "Brutal Impact",
					column = 1,
					row = 5,
					icon = 132114,
					ranks = 2,
				},
			}, -- [13]
			{
				info = {
					tips = "Teaches Feral Charge (Bear) and Feral Charge (Cat).\r\n\r\nFeral Charge (Bear) - Causes you to charge an enemy, immobilizing and interrupting any spell being cast for 4 sec. This ability can be used in Bear Form and Dire Bear Form. 15 second cooldown.\r\n\r\nFeral Charge (Cat) - Causes you to leap behind an enemy, dazing them for 3 sec. 30 second cooldown.",
					name = "Feral Charge",
					column = 3,
					row = 5,
					icon = 132183,
					ranks = 1,
				},
			}, -- [14]
			{
				info = {
					tips = "Increases your healing spells by up to %d%% of your Agility, and increases healing done to you by %d%% while in Cat form.",
					tipValues = {{35, 10}, {70, 20}},
					name = "Nurturing Instinct",
					column = 4,
					row = 5,
					icon = 132130,
					ranks = 2,
				},
			}, -- [15]
			{
				info = {
					tips = "Increases your dodge while in Bear Form or Dire Bear Form by %d%%, and you regenerate %d rage every time you dodge while in Bear Form or Dire Bear Form.",
					tipValues = {{2, 1}, {4, 2}, {6, 3}},
					name = "Natural Reaction",
					column = 1,
					row = 6,
					icon = 132091,
					ranks = 3,
				},
			}, -- [16]
			{
				info = {
					tips = "Increases your Intellect by %d%%.  In addition, while in Bear or Dire Bear Form your Stamina is increased by %d%% and while in Cat Form your attack power is increased by %d%%.",
					tipValues = {{4, 2, 2}, {8, 4, 4}, {12, 6, 6}, {16, 8, 8}, {20, 10, 10}},
					prereqs = {
						{
							column = 2,
							row = 4,
							source = 10,
						}, -- [1]
						{
						}, -- [2]
					},
					name = "Heart of the Wild",
					column = 2,
					row = 6,
					icon = 135879,
					ranks = 5,
				},
			}, -- [17]
			{
				info = {
					tips = "Increases all attributes by %d%%, reduces the chance you'll be critically hit by melee attacks by %d%%, and increases your armor contribution from cloth and leather items in Bear Form and Dire Bear Form by %d%%.",
					tipValues = {{2, 2, 11}, {4, 4, 22}, {6, 6, 33}},
					name = "Survival of the Fittest",
					column = 3,
					row = 6,
					icon = 132126,
					ranks = 3,
				},
			}, -- [18]
			{
				info = {
					tips = "While in Cat, Bear or Dire Bear Form, the Leader of the Pack increases ranged and melee critical chance of all party and raid members within 100 yards by 5%%.",
					name = "Leader of the Pack",
					exceptional = 1,
					column = 2,
					row = 7,
					icon = 136112,
					ranks = 1,
				},
			}, -- [19]
			{
				info = {
					tips = "Your Leader of the Pack ability also causes affected targets to heal themselves for %d%% of their total health when they critically hit with a melee or ranged attack.  The healing effect cannot occur more than once every 6 sec.  In addition, you gain %d%% of your maximum mana when you benefit from this heal.",
					tipValues = {{2, 4}, {4, 8}},
					prereqs = {
						{
							column = 2,
							row = 7,
							source = 19,
						}, -- [1]
						{
						}, -- [2]
					},
					name = "Improved Leader of the Pack",
					column = 3,
					row = 7,
					icon = 136112,
					ranks = 2,
				},
			}, -- [20]
			{
				info = {
					tips = "Reduces the duration of fear effects by %d%%, reduces all damage taken while stunned by %d%% while in Cat Form.",
					tipValues = {{10, 10}, {20, 20}, {30, 30}},
					name = "Primal Tenacity",
					column = 4,
					row = 7,
					icon = 132139,
					ranks = 3,
				},
			}, -- [21]
			{
				info = {
					tips = "Increases your attack power by %d%% and reduces the damage you take by %d%%, while in Bear or Dire Bear Form.",
					tipValues = {{2, 4}, {4, 8}, {6, 12}},
					prereqs = {
						{
							column = 2,
							row = 7,
							source = 19,
						}, -- [1]
						{
						}, -- [2]
					},
					name = "Protector of the Pack",
					column = 1,
					row = 8,
					icon = 132117,
					ranks = 3,
				},
			}, -- [22]
			{
				info = {
					tips = "While in Cat Form increases your damage from melee critical strikes by %d%% and reduces the damage taken from area of effect attacks by %d%%.",
					tipValues = {{3, 10}, {7, 20}, {10, 30}},
					name = "Predatory Instincts",
					column = 3,
					row = 8,
					icon = 132138,
					ranks = 3,
				},
			}, -- [23]
			{
				info = {
					tips = "Your Shred, Maul, and Mangle attacks cause an Infected Wound in the target. The Infected Wound reduces the movement speed of the target by %d%% and the attack speed by %d%%. Lasts 12 sec.",
					tipValues = {{16, 6}, {34, 14}, {50, 20}},
					name = "Infected Wounds",
					column = 4,
					row = 8,
					icon = 236158,
					ranks = 3,
				},
			}, -- [24]
			{
				info = {
					tips = "While using your Enrage ability in Bear Form or Dire Bear Form, your damage is increased by %d%%, and your Tiger's Fury ability also instantly restores %d energy.  In addition, the mana cost of Bear Form, Cat Form, and Dire Bear Form is reduced by %d%%.",
					tipValues = {{5, 20, 20}, {10, 40, 40}, {15, 60, 60}},
					name = "King of the Jungle",
					column = 1,
					row = 9,
					icon = 236159,
					ranks = 3,
				},
			}, -- [25]
			{
				info = {
					tips = "Mangle the target, inflicting damage and causing the target to take additional damage from bleed effects for 1 min.  This ability can be used in Cat Form or Dire Bear Form.",
					prereqs = {
						{
							column = 2,
							row = 7,
							source = 19,
						}, -- [1]
						{
						}, -- [2]
					},
					name = "Mangle",
					column = 2,
					row = 9,
					icon = 132135,
					ranks = 1,
				},
			}, -- [26]
			{
				info = {
					tips = "Reduces the cooldown of your Mangle (Bear) ability by %.1f sec., and reduces the energy cost of your Mangle (Cat) ability by %d.",
					tipValues = {{0.5, 2}, {1.0, 4}, {1.5, 6}},
					prereqs = {
						{
							column = 2,
							row = 9,
							source = 26,
						}, -- [1]
						{
						}, -- [2]
					},
					name = "Improved Mangle",
					column = 3,
					row = 9,
					icon = 132135,
					ranks = 3,
				},
			}, -- [27]
			{
				info = {
					tips = "Increases damage done by your Maul and Shred attacks on bleeding targets by %d%%, and increases the critical strike chance of your Ferocious Bite ability on bleeding targets by %d%%.",
					tipValues = {{4, 5}, {8, 10}, {12, 15}, {16, 20}, {20, 25}},
					name = "Rend and Tear",
					column = 2,
					row = 10,
					icon = 236164,
					ranks = 5,
				},
			}, -- [28]
			{
				info = {
					tips = "Grants the periodic damage from your Lacerate and Rip abilities the ability to critically hit.",
					prereqs = {
						{
							column = 2,
							row = 10,
							source = 28,
						}, -- [1]
						{
						}, -- [2]
					},
					name = "Primal Gore",
					column = 3,
					row = 10,
					icon = 132140,
					ranks = 1,
				},
			}, -- [29]
			{
				info = {
					tips = "When activated, this ability causes your Mangle (Bear) ability to hit up to 3 targets and have no cooldown, and reduces the energy cost of all your Cat Form abilities by 50%%.  Lasts 15 sec.  You cannot use Tiger's Fury while Berserk is active. \r\n\r\nClears the effect of Fear and makes you immune to Fear for the duration.",
					name = "Berserk",
					exceptional = 1,
					column = 2,
					row = 11,
					icon = 236149,
					ranks = 1,
				},
			}, -- [30]
		},
		info = {
			background = "DruidFeralCombat",
			name = "Feral Combat",
			icon = 132276,
		},
	}, -- [2]
	{
		numtalents = 27,
		talents = {
			{
				info = {
					tips = "Increases the effects of your Mark of the Wild and Gift of the Wild spells by %d%%, and increases all of your total attributes by %d%%.",
					tipValues = {{20, 1}, {40, 2}},
					name = "Improved Mark of the Wild",
					column = 1,
					row = 1,
					icon = 136078,
					ranks = 2,
				},
			}, -- [1]
			{
				info = {
					tips = "Reduces the pushback suffered from damaging attacks  while casting Healing Touch, Wrath, Entangling Roots, Cyclone, Nourish, Regrowth and Tranquility by %d%%.",
					tipValues = {{23}, {46}, {70}},
					name = "Nature's Focus",
					column = 2,
					row = 1,
					icon = 136042,
					ranks = 3,
				},
			}, -- [2]
			{
				info = {
					tips = "Gives you %d%% chance to gain 10 Rage when you shapeshift into Bear and Dire Bear Form, and you keep up to %d of your Energy when you shapeshift into Cat Form, and increases your total Intellect while in Moonkin form by %d%%.",
					tipValues = {{20, 20, 2}, {40, 40, 4}, {60, 60, 6}, {80, 80, 8}, {100, 100, 10}},
					name = "Furor",
					column = 3,
					row = 1,
					icon = 135881,
					ranks = 5,
				},
			}, -- [3]
			{
				info = {
					tips = "Reduces the cast time of your Healing Touch spell by %.1f sec and increases the damage you deal with physical attacks in all forms by %d%%.",
					tipValues = {{0.1, 2}, {0.2, 4}, {0.3, 6}, {0.4, 8}, {0.5, 10}},
					name = "Naturalist",
					column = 1,
					row = 2,
					icon = 136041,
					ranks = 5,
				},
			}, -- [4]
			{
				info = {
					tips = "Reduces the threat generated by your restoration spells by %d%% and reduces the chance your helpful spells, Moonfire, and Insect Swarm will be dispelled by %d%%.",
					tipValues = {{10, 10}, {20, 20}, {30, 30}},
					name = "Subtlety",
					column = 2,
					row = 2,
					icon = 132150,
					ranks = 3,
				},
			}, -- [5]
			{
				info = {
					tips = "Reduces the mana cost of all shapeshifting by %d%%.",
					tipValues = {{10}, {20}, {30}},
					name = "Natural Shapeshifter",
					column = 3,
					row = 2,
					icon = 136116,
					ranks = 3,
				},
			}, -- [6]
			{
				info = {
					tips = "Allows %d%% of your Mana regeneration to continue while casting and causes your Enrage ability to instantly generate %d rage.",
					tipValues = {{17, 4}, {33, 7}, {50, 10}},
					name = "Intensity",
					column = 1,
					row = 3,
					icon = 135863,
					ranks = 3,
				},
			}, -- [7]
			{
				info = {
					tips = "Each of the Druid's damage spells, healing spells, and auto attacks has a chance of causing the caster to enter a Clearcasting state.  The Clearcasting state reduces the Mana, Rage or Energy cost of your next damage, healing spell or offensive ability by 100%%.",
					name = "Omen of Clarity",
					column = 2,
					row = 3,
					icon = 136017,
					ranks = 1,
				},
			}, -- [8]
			{
				info = {
					tips = "Grants an effect which lasts while the Druid is within the respective shapeshift form.\r\n\r\nBear Form - Increases physical damage by %d%%.\r\n\r\nCat Form - Increases critical strike chance by %d%%.\r\n\r\nMoonkin Form - Increases spell damage by %d%%.\r\n\r\nTree of Life Form - Increases healing by %d%%.",
					tipValues = {{2, 2, 2, 2}, {4, 4, 4, 4}},
					prereqs = {
						{
							column = 3,
							row = 2,
							source = 6,
						}, -- [1]
						{
						}, -- [2]
					},
					name = "Master Shapeshifter",
					column = 3,
					row = 3,
					icon = 236161,
					ranks = 2,
				},
			}, -- [9]
			{
				info = {
					tips = "Reduces the mana cost of your Healing Touch, Nourish and Tranquility spells by %d%%.",
					tipValues = {{2}, {4}, {6}, {8}, {10}},
					name = "Tranquil Spirit",
					column = 2,
					row = 4,
					icon = 135900,
					ranks = 5,
				},
			}, -- [10]
			{
				info = {
					tips = "Increases the effect of your Rejuvenation spell by %d%%.",
					tipValues = {{5}, {10}, {15}},
					name = "Improved Rejuvenation",
					column = 3,
					row = 4,
					icon = 136081,
					ranks = 3,
				},
			}, -- [11]
			{
				info = {
					tips = "When activated, your next Nature spell with a base casting time less than 10 sec. becomes an instant cast spell.",
					prereqs = {
						{
							column = 1,
							row = 3,
							source = 7,
						}, -- [1]
						{
						}, -- [2]
					},
					name = "Nature's Swiftness",
					exceptional = 1,
					column = 1,
					row = 5,
					icon = 136076,
					ranks = 1,
				},
			}, -- [12]
			{
				info = {
					tips = "Increases the effect of all healing spells by %d%%.",
					tipValues = {{2}, {4}, {6}, {8}, {10}},
					name = "Gift of Nature",
					column = 2,
					row = 5,
					icon = 136074,
					ranks = 5,
				},
			}, -- [13]
			{
				info = {
					tips = "Reduces threat caused by Tranquility by %d%%, and reduces the cooldown by %d%%.",
					tipValues = {{50, 30}, {100, 60}},
					name = "Improved Tranquility",
					column = 4,
					row = 5,
					icon = 136107,
					ranks = 2,
				},
			}, -- [14]
			{
				info = {
					tips = "Your Healing Touch spell gains an additional %d%% and your Nourish spell gains an additional %d%% of your bonus healing effects.",
					tipValues = {{20, 10}, {40, 20}},
					name = "Empowered Touch",
					column = 1,
					row = 6,
					icon = 132125,
					ranks = 2,
				},
			}, -- [15]
			{
				info = {
					tips = "Increases the critical effect chance of your Regrowth and Nourish spells by %d%%.",
					tipValues = {{5}, {10}, {15}, {20}, {25}},
					prereqs = {
						{
							column = 3,
							row = 4,
							source = 11,
						}, -- [1]
						{
						}, -- [2]
					},
					name = "Nature's Bounty",
					column = 3,
					row = 6,
					icon = 136085,
					ranks = 5,
				},
			}, -- [16]
			{
				info = {
					tips = "Increases your total Spirit by %d%%.",
					tipValues = {{5}, {10}, {15}},
					name = "Living Spirit",
					column = 1,
					row = 7,
					icon = 136037,
					ranks = 3,
				},
			}, -- [17]
			{
				info = {
					tips = "Consumes a Rejuvenation or Regrowth effect on a friendly target to instantly heal them an amount equal to 12 sec. of Rejuvenation or 18 sec. of Regrowth.",
					prereqs = {
						{
							column = 2,
							row = 5,
							source = 13,
						}, -- [1]
						{
						}, -- [2]
					},
					name = "Swiftmend",
					exceptional = 1,
					column = 2,
					row = 7,
					icon = 134914,
					ranks = 1,
				},
			}, -- [18]
			{
				info = {
					tips = "Your critical strike chance with all spells is increased by %d%% and critical strikes against you give you the Natural Perfection effect reducing all damage taken by %d%%.  Stacks up to 3 times.  Lasts 8 sec.",
					tipValues = {{1, 2}, {2, 3}, {3, 4}},
					name = "Natural Perfection",
					column = 3,
					row = 7,
					icon = 132137,
					ranks = 3,
				},
			}, -- [19]
			{
				info = {
					tips = "The bonus healing effects of your healing over time spells is increased by %d%%.",
					tipValues = {{4}, {8}, {12}, {16}, {20}},
					name = "Empowered Rejuvenation",
					column = 2,
					row = 8,
					icon = 132124,
					ranks = 5,
				},
			}, -- [20]
			{
				info = {
					tips = "When you critically heal your target with Swiftmend, Regrowth, Nourish or Healing Touch spell you have a %d%% chance to plant a Living Seed on the target for 30%% of the amount healed. The Living Seed will bloom when the target is next attacked. Lasts 15 sec.",
					tipValues = {{33}, {66}, {100}},
					name = "Living Seed",
					column = 3,
					row = 8,
					icon = 236155,
					ranks = 3,
				},
			}, -- [21]
			{
				info = {
					tips = "Your Rejuvenation and Wild Growth spells have a %d%% chance to restore 8 Energy, 4 Rage, 1%% Mana or 16 Runic Power per tick.",
					tipValues = {{5}, {10}, {15}},
					name = "Revitalize",
					column = 1,
					row = 9,
					icon = 236166,
					ranks = 3,
				},
			}, -- [22]
			{
				info = {
					tips = "Reduces the mana cost of your healing over time spells by 20%% and grants the ability to shapeshift into the Tree of Life. While in this form you increase healing received by 6%% for all party and raid members within 100 yards, and you can only cast Restoration spells in addition to Innervate, Barkskin, Nature's Grasp and Thorns spells.\r\n\r\nThe act of shapeshifting frees the caster of Polymorph and Movement Impairing effects.",
					prereqs = {
						{
							column = 2,
							row = 8,
							source = 20,
						}, -- [1]
						{
						}, -- [2]
					},
					name = "Tree of Life",
					exceptional = 1,
					column = 2,
					row = 9,
					icon = 132145,
					ranks = 1,
				},
			}, -- [23]
			{
				info = {
					tips = "Increases your armor contribution from items while in Tree of Life Form by %d%%, and increases your healing spell power by %d%% of your spirit while in Tree of Life Form.",
					tipValues = {{67, 5}, {133, 10}, {200, 15}},
					prereqs = {
						{
							column = 2,
							row = 9,
							source = 23,
						}, -- [1]
						{
						}, -- [2]
					},
					name = "Improved Tree of Life",
					column = 3,
					row = 9,
					icon = 236157,
					ranks = 3,
				},
			}, -- [24]
			{
				info = {
					tips = "Grants %d%% additional armor contribution from cloth and leather items while in Travel Form or while not shapeshifted, increases the damage reduction granted by your Barkskin spell by %d%% and reduces the chance your Barkskin is dispelled by %d%%.",
					tipValues = {{80, 5, 35}, {160, 10, 70}},
					name = "Improved Barkskin",
					column = 1,
					row = 10,
					icon = 136097,
					ranks = 2,
				},
			}, -- [25]
			{
				info = {
					tips = "Increases your total spell haste by %d%% and reduces your global cooldown by %d%% when casting Lifebloom.",
					tipValues = {{2, 2}, {4, 4}, {6, 6}, {8, 8}, {10, 10}},
					name = "Gift of the Earthmother",
					column = 3,
					row = 10,
					icon = 236160,
					ranks = 5,
				},
			}, -- [26]
			{
				info = {
					tips = "Heals up to 5 friendly party or raid members within 15 yards of the target for 686 over 7 sec. The amount healed is applied quickly at first, and slows down as the Wild Growth reaches its full duration.",
					prereqs = {
						{
							column = 2,
							row = 9,
							source = 23,
						}, -- [1]
						{
						}, -- [2]
					},
					name = "Wild Growth",
					exceptional = 1,
					column = 2,
					row = 11,
					icon = 236153,
					ranks = 1,
				},
			}, -- [27]
		},
		info = {
			background = "DruidRestoration",
			name = "Restoration",
			icon = 136041,
		},
	}, -- [3]
}
