if not Talented_Data then return end

Talented_Data.PRIEST = {
	{
		numtalents = 15,
		talents = {
			{
				info = {
					name = "Unbreakable Will",
					ranks = 5,
					column = 2,
					icon = 135995,
					row = 1,
					tips = "Increases your chance to resist Stun, Fear, and Silence effects by an additional %d%%.",
					tipValues = {{3}, {6}, {9}, {12}, {15}}
				},
			}, -- [1]
			{
				info = {
					name = "Wand Specialization",
					ranks = 5,
					column = 3,
					icon = 135463,
					row = 1,
					tips = "Increases your damage with Wands by %d%%.",
					tipValues = {{5}, {10}, {15}, {20}, {25}}
				},
			}, -- [2]
			{
				info = {
					name = "Silent Resolve",
					ranks = 5,
					column = 1,
					icon = 136053,
					row = 2,
					tips = "Reduces the threat generated by your spells by %d%%.",
					tipValues = {{4}, {8}, {12}, {16}, {20}}
				},
			}, -- [3]
			{
				info = {
					name = "Improved Power Word: Fortitude",
					ranks = 2,
					column = 2,
					icon = 135987,
					row = 2,
					tips = "Increases the effect of your Power Word: Fortitude and Prayer of Fortitude spells by %d%%.",
					tipValues = {{15}, {30}}
				},
			}, -- [4]
			{
				info = {
					name = "Improved Power Word: Shield",
					ranks = 3,
					column = 3,
					icon = 135940,
					row = 2,
					tips = "Increases the damage absorbed by your Power Word: Shield by %d%%.",
					tipValues = {{5}, {10}, {15}}
				},
			}, -- [5]
			{
				info = {
					name = "Martyrdom",
					ranks = 2,
					column = 4,
					icon = 136107,
					row = 2,
					tips = "Gives you a %d%% chance to gain the Focused Casting effect that lasts for 6 sec after being the victim of a melee or ranged critical strike.  The Focused Casting effect prevents you from losing casting time when taking damage and increases resistance to Interrupt effects by %d%%.",
					tipValues = {{50, 10}, {100, 20}}
				},
			}, -- [6]
			{
				info = {
					ranks = 1,
					tipValues = {},
					name = "Inner Focus",
					icon = 135863,
					column = 2,
					exceptional = 1,
					row = 3,
					tips = "When activated, reduces the Mana cost of your next spell by 100%% and increases its critical effect chance by 25%% if it is capable of a critical effect.",
				},
			}, -- [7]
			{
				info = {
					name = "Meditation",
					ranks = 3,
					column = 3,
					icon = 136090,
					row = 3,
					tips = "Allows %d%% of your Mana regeneration to continue while casting.",
					tipValues = {{5}, {10}, {15}}
				},
			}, -- [8]
			{
				info = {
					name = "Improved Inner Fire",
					ranks = 3,
					column = 1,
					icon = 135926,
					row = 4,
					tips = "Increases the Armor bonus of your Inner Fire spell by %d%%.",
					tipValues = {{10}, {20}, {30}}
				},
			}, -- [9]
			{
				info = {
					name = "Mental Agility",
					ranks = 5,
					column = 2,
					icon = 132156,
					row = 4,
					tips = "Reduces the mana cost of your instant cast spells by %d%%.",
					tipValues = {{2}, {4}, {6}, {8}, {10}}
				},
			}, -- [10]
			{
				info = {
					name = "Improved Mana Burn",
					ranks = 2,
					column = 4,
					icon = 136170,
					row = 4,
					tips = "Reduces the casting time of your Mana Burn spell by %.2f secs.",
					tipValues = {{0.25}, {0.50}}
				},
			}, -- [11]
			{
				info = {
					name = "Mental Strength",
					ranks = 5,
					column = 2,
					icon = 136031,
					row = 5,
					tips = "Increases your maximum Mana by %d%%.",
					tipValues = {{2}, {4}, {6}, {8}, {10}}
				},
			}, -- [12]
			{
				info = {
					ranks = 1,
					tipValues = {},
					prereqs = {
						{
							column = 3,
							row = 3,
							source = 8,
						}, -- [1]
					},
					name = "Divine Spirit",
					icon = 135898,
					column = 3,
					exceptional = 1,
					row = 5,
					tips = "Holy power infuses the target, increasing their Spirit by 17 for 30 min.",
				},
			}, -- [13]
			{
				info = {
					name = "Force of Will",
					ranks = 5,
					column = 3,
					icon = 136092,
					row = 6,
					tips = "Increases your spell damage by %d%% and the critical strike chance of your offensive spells by %d%%.",
					tipValues = {{1, 1}, {2, 2}, {3, 3}, {4, 4}, {5, 5}}
				},
			}, -- [14]
			{
				info = {
					ranks = 1,
					tipValues = {},
					prereqs = {
						{
							column = 2,
							row = 5,
							source = 12,
						}, -- [1]
					},
					name = "Power Infusion",
					icon = 135939,
					column = 2,
					exceptional = 1,
					row = 7,
					tips = "Infuses the target with power, increasing their spell damage and healing by 20%%.  Lasts 15 sec.",
				},
			}, -- [15]
		},
		info = {
			name = "Discipline",
			background = "PriestDiscipline",
		},
	}, -- [1]
	{
		numtalents = 16,
		talents = {
			{
				info = {
					name = "Healing Focus",
					ranks = 2,
					column = 1,
					icon = 135918,
					row = 1,
					tips = "Gives you a %d%% chance to avoid interruption caused by damage while casting any healing spell.",
					tipValues = {{35}, {70}}
				},
			}, -- [1]
			{
				info = {
					name = "Improved Renew",
					ranks = 3,
					column = 2,
					icon = 135953,
					row = 1,
					tips = "Increases the amount healed by your Renew spell by %d%%.",
					tipValues = {{5}, {10}, {15}}
				},
			}, -- [2]
			{
				info = {
					name = "Holy Specialization",
					ranks = 5,
					column = 3,
					icon = 135967,
					row = 1,
					tips = "Increases the critical effect chance of your Holy spells by %d%%.",
					tipValues = {{1}, {2}, {3}, {4}, {5}}
				},
			}, -- [3]
			{
				info = {
					name = "Spell Warding",
					ranks = 5,
					column = 2,
					icon = 135976,
					row = 2,
					tips = "Reduces all spell damage taken by %d%%.",
					tipValues = {{2}, {4}, {6}, {8}, {10}}
				},
			}, -- [4]
			{
				info = {
					name = "Divine Fury",
					ranks = 5,
					column = 3,
					icon = 135971,
					row = 2,
					tips = "Reduces the casting time of your Smite, Holy Fire, Heal and Greater Heal spells by %.1f sec.",
					tipValues = {{0.1}, {0.2}, {0.3}, {0.4}, {0.5}}
				},
			}, -- [5]
			{
				info = {
					ranks = 1,
					tipValues = {},
					name = "Holy Nova",
					icon = 135922,
					column = 1,
					exceptional = 1,
					row = 3,
					tips = "Causes an explosion of holy light around the caster, causing 28 to 32 Holy damage to all enemy targets within 10 yards and healing all party members within 10 yards for 52 to 60.  These effects cause no threat.",
				},
			}, -- [6]
			{
				info = {
					name = "Blessed Recovery",
					ranks = 3,
					column = 2,
					icon = 135877,
					row = 3,
					tips = "After being struck by a melee or ranged critical hit, heal %d%% of the damage taken over 6 sec.",
					tipValues = {{8}, {16}, {25}}
				},
			}, -- [7]
			{
				info = {
					name = "Inspiration",
					ranks = 3,
					column = 4,
					icon = 135928,
					row = 3,
					tips = "Increases your target's armor by %d%% for 15 sec after getting a critical effect from your Flash Heal, Heal, Greater Heal, or Prayer of Healing spell.",
					tipValues = {{8}, {16}, {25}}
				},
			}, -- [8]
			{
				info = {
					name = "Holy Reach",
					ranks = 2,
					column = 1,
					icon = 135949,
					row = 4,
					tips = "Increases the range of your Smite and Holy Fire spells and the radius of your Prayer of Healing and Holy Nova spells by %d%%.",
					tipValues = {{10}, {20}}
				},
			}, -- [9]
			{
				info = {
					name = "Improved Healing",
					ranks = 3,
					column = 2,
					icon = 135916,
					row = 4,
					tips = "Reduces the Mana cost of your Lesser Heal, Heal, and Greater Heal spells by %d%%.",
					tipValues = {{5}, {10}, {15}}
				},
			}, -- [10]
			{
				info = {
					prereqs = {
						{
							column = 3,
							row = 2,
							source = 5,
						}, -- [1]
					},
					name = "Searing Light",
					ranks = 2,
					column = 3,
					icon = 135973,
					row = 4,
					tips = "Increases the damage of your Smite and Holy Fire spells by %d%%.",
					tipValues = {{5}, {10}}
				},
			}, -- [11]
			{
				info = {
					name = "Improved Prayer of Healing",
					ranks = 2,
					column = 1,
					icon = 135943,
					row = 5,
					tips = "Reduces the Mana cost of your Prayer of Healing spell by %d%%.",
					tipValues = {{10}, {20}}
				},
			}, -- [12]
			{
				info = {
					ranks = 1,
					tipValues = {},
					name = "Spirit of Redemption",
					icon = 132864,
					column = 2,
					exceptional = 1,
					row = 5,
					tips = "Upon death, the priest becomes the Spirit of Redemption for 10 sec.  The Spirit of Redemption cannot move, attack, be attacked or targeted by any spells or effects.  While in this form the priest can cast any healing spell free of cost.  When the effect ends, the priest dies.",
				},
			}, -- [13]
			{
				info = {
					name = "Spiritual Guidance",
					ranks = 5,
					column = 3,
					icon = 135977,
					row = 5,
					tips = "Increases spell damage and healing by up to %d%% of your total Spirit.",
					tipValues = {{5}, {10}, {15}, {20}, {25}}
				},
			}, -- [14]
			{
				info = {
					name = "Spiritual Healing",
					ranks = 5,
					column = 3,
					icon = 136057,
					row = 6,
					tips = "Increases the amount healed by your healing spells by %d%%.",
					tipValues = {{2}, {4}, {6}, {8}, {10}}
				},
			}, -- [15]
			{
				info = {
					ranks = 1,
					tipValues = {},
					prereqs = {
						{
							column = 2,
							row = 5,
							source = 13,
						}, -- [1]
					},
					name = "Lightwell",
					icon = 135980,
					column = 2,
					exceptional = 1,
					row = 7,
					tips = "Creates a holy Lightwell near the priest.  Members of your raid or party can click the Lightwell to restore 800 health over 10 sec.  Being attacked cancels the effect.  Lightwell lasts for 3 min or 5 charges.",
				},
			}, -- [16]
		},
		info = {
			name = "Holy",
			background = "PriestHoly",
		},
	}, -- [2]
	{
		numtalents = 16,
		talents = {
			{
				info = {
					name = "Spirit Tap",
					ranks = 5,
					column = 2,
					icon = 136188,
					row = 1,
					tips = "Gives you a %d%% chance to gain a 100%% bonus to your Spirit after killing a target that yields experience.  For the duration, your Mana will regenerate at a 50%% rate while casting.  Lasts 15 sec.",
					tipValues = {{20}, {40}, {60}, {80}, {100}}
				},
			}, -- [1]
			{
				info = {
					name = "Blackout",
					ranks = 5,
					column = 3,
					icon = 136160,
					row = 1,
					tips = "Gives your Shadow damage spells a %d%% chance to stun the target for 3 sec.",
					tipValues = {{2}, {4}, {6}, {8}, {10}},
				},
			}, -- [2]
			{
				info = {
					name = "Shadow Affinity",
					ranks = 3,
					column = 1,
					icon = 136205,
					row = 2,
					tips = "Reduces the threat generated by your Shadow spells by %d%%.",
					tipValues = {{8}, {16}, {25}}
				},
			}, -- [3]
			{
				info = {
					name = "Improved Shadow Word: Pain",
					ranks = 2,
					column = 2,
					icon = 136207,
					row = 2,
					tips = "Increases the duration of your Shadow Word: Pain spell by %d sec.",
					tipValues = {{3}, {6}}
				},
			}, -- [4]
			{
				info = {
					name = "Shadow Focus",
					ranks = 5,
					column = 3,
					icon = 136126,
					row = 2,
					tips = "Reduces your target's chance to resist your Shadow spells by %d%%.",
					tipValues = {{2}, {4}, {6}, {8}, {10}}
				},
			}, -- [5]
			{
				info = {
					name = "Improved Psychic Scream",
					ranks = 2,
					column = 1,
					icon = 136184,
					row = 3,
					tips = "Reduces the cooldown of your Psychic Scream spell by %d sec.",
					tipValues = {{2}, {4}}
				},
			}, -- [6]
			{
				info = {
					name = "Improved Mind Blast",
					ranks = 5,
					column = 2,
					icon = 136224,
					row = 3,
					tips = "Reduces the cooldown of your Mind Blast spell by %.1f sec.",
					tipValues = {{0.5}, {1.0}, {1.5}, {2.0}, {2.5}}
				},
			}, -- [7]
			{
				info = {
					ranks = 1,
					tipValues = {},
					name = "Mind Flay",
					icon = 136208,
					column = 3,
					exceptional = 1,
					row = 3,
					tips = "Assault the target's mind with Shadow energy, causing 75 Shadow damage over 3 sec and slowing their movement speed by 50%%.",
				},
			}, -- [8]
			{
				info = {
					name = "Improved Fade",
					ranks = 2,
					column = 2,
					icon = 135994,
					row = 4,
					tips = "Decreases the cooldown of your Fade ability by %d sec.",
					tipValues = {{3}, {6}}
				},
			}, -- [9]
			{
				info = {
					name = "Shadow Reach",
					ranks = 3,
					column = 3,
					icon = 136130,
					row = 4,
					tips = "Increases the range of your Shadow damage spells by %d%%.",
					tipValues = {{6}, {13}, {20}}
				},
			}, -- [10]
			{
				info = {
					name = "Shadow Weaving",
					ranks = 5,
					column = 4,
					icon = 136123,
					row = 4,
					tips = "Your Shadow damage spells have a %d%% chance to cause your target to be vulnerable to Shadow damage.  This vulnerability increases the Shadow damage dealt to your target by 3%% and lasts 15 sec.  Stacks up to 5 times.",
					tipValues = {{20}, {40}, {60}, {80}, {100}}
				},
			}, -- [11]
			{
				info = {
					ranks = 1,
					tipValues = {},
					prereqs = {
						{
							column = 1,
							row = 3,
							source = 6,
						}, -- [1]
					},
					name = "Silence",
					icon = 136164,
					column = 1,
					exceptional = 1,
					row = 5,
					tips = "Silences the target, preventing them from casting spells for 5 sec.",
				},
			}, -- [12]
			{
				info = {
					ranks = 1,
					tipValues = {},
					name = "Vampiric Embrace",
					icon = 136230,
					column = 2,
					exceptional = 1,
					row = 5,
					tips = "Afflicts your target with Shadow energy that causes all party members to be healed for 20%% of any Shadow spell damage you deal for 1 min.",
				},
			}, -- [13]
			{
				info = {
					prereqs = {
						{
							column = 2,
							row = 5,
							source = 13,
						}, -- [1]
					},
					name = "Improved Vampiric Embrace",
					ranks = 2,
					column = 3,
					icon = 136165,
					row = 5,
					tips = "Increases the percentage healed by Vampiric Embrace by an additional %d%%.",
					tipValues = {{5}, {10}}
				},
			}, -- [14]
			{
				info = {
					name = "Darkness",
					ranks = 5,
					column = 3,
					icon = 136223,
					row = 6,
					tips = "Increases your Shadow spell damage by %d%%.",
					tipValues = {{2}, {4}, {6}, {8}, {10}}
				},
			}, -- [15]
			{
				info = {
					ranks = 1,
					tipValues = {},
					prereqs = {
						{
							column = 2,
							row = 5,
							source = 13,
						}, -- [1]
					},
					name = "Shadowform",
					icon = 136200,
					column = 2,
					exceptional = 1,
					row = 7,
					tips = "Assume a Shadowform, increasing your Shadow damage by 15%% and reducing Physical damage done to you by 15%%.  However, you may not cast Holy spells while in this form.",
				},
			}, -- [16]
		},
		info = {
			name = "Shadow",
			background = "PriestShadow",
		},
	} -- [3]
}
